config/routes.rb
SupercarIndexBricks::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

  resources :supercars do 
    collection do 
      get :tag
    end 
  end 

  resources :makes do 
    collection do 
      get :tag
    end 
  end

  resources :car_models do 
    collection do 
      get :tag
    end 
  end

  resources :cities do 
    collection do 
      get :tag
    end 
  end

  resources :countries do 
    collection do 
      get :tag
    end 
  end

  get 'makes/tags/:tag', to: 'makes#index', as: :makes_tag
  get 'models/tags/:tag', to: 'car_models#index', as: :models_tag
  get 'cities/tags/:tag', to: 'cities#index', as: :cities_tag
  get 'countries/tags/:tag', to: 'countries#index', as: :countries_tag

end

app/models/supercar.rb
class Supercar < ActiveRecord::Base

	has_one :make
	has_one :car_model
	has_one :city
	has_one :country
	has_one :spot_type

	has_one :rank

	belongs_to :user
	
	accepts_nested_attributes_for :make, :car_model, :city, :country
	validates_presence_of :img_url, :on => :create	
	validates_format_of :img_url, :with => /instagram\.com\/p\/*/

	# e.g validates_format_of :video_link, :with => /youtu\.be\/([^\?]*)/ || /^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/


end

app/controllers/supercars_controller.rb
class SupercarsController < ApplicationController

	def index	 
		@supercars = Supercar.all.paginate(:page => params[:page], :per_page => 9).order("created_at DESC")
	end
	def new
		@supercar = Supercar.new
		@supercar.make = Make.new
		@supercar.car_model = CarModel.new
		@supercar.city = City.new
		@supercar.country = Country.new
		@supercar.spot_type = SpotType.new
	end

	def show
		@supercar = Supercar.find(params[:id])

		if current_user
			
		end
	end

	def edit
  		@supercar = Supercar.find(params[:id])
	end

	def update
	  @supercar = Supercar.find(params[:id])
	  @supercar.update(supercar_params)
	  @supercar.make.update(make_params)

	  @supercar.car_model.update(car_model_params)

	  @supercar.city.update(city_params)
	  @supercar.country.update(country_params)
	  # @supercar.spot_type.update(spot_type_params)

	    if @supercar.update_attributes(supercar_params)
	      flash[:success] = "Supercar updated"
	      redirect_to @supercar
	    else
	      render 'edit'
	    end
	end


	def create


		@supercar = Supercar.new(supercar_params)
		@supercar.make = Make.new(make_params, :parse => true)
		@supercar.car_model = CarModel.new(car_model_params, :parse => true)
		@supercar.city = City.new(city_params)
		@supercar.country = Country.new(country_params)
		# @supercar.spot_type = SpotType.new(spot_type_params)

		if current_user
			@supercar.user = current_user
		else
		end

	  	if @supercar.save
	  		redirect_to supercars_url
	  	else
	  		render :new
	  	end

	end
	
def destroy
end


	private
	def supercar_params
	 params.require(:supercar).permit(:img_url)
	end
	def make_params
	 # params.require(:make).permit(:name, { tag_list: [] }, :parse => true).permit!
	 params.require(:make).permit(:name, :tag_list)
	end
	def car_model_params
	 # params.require(:car_model).permit(:name, { tag_list: [] }, :parse => true).permit!
	 params.require(:car_model).permit(:name, :tag_list)
	end
	def city_params
	 params.require(:city).permit(:name, :tag_list)
	end
	def country_params
	 params.require(:country).permit(:name, :tag_list)
	end
	def spot_type_params
	 # params.require(:spot_type).permit(:name, :tag_list)
	end

	end

app/helpers/supercars_helper.rb
module SupercarsHelper
	require "oembed"
end

app/views/supercars/_supercar_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Enrlarge(er than life)
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">

<%= render :inline => supercar.img_url %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/supercars/edit.html.erb
<%= form_for([@supercar]) do |f| %>

  <% if @supercar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supercar.errors.count, "error") %> prohibited this supercar from being saved:</h2>

      <ul>
      <% @supercar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <% end %>

 <%= fields_for(@supercar.make) do |m| %>
 <div class="field">
   <%= m.label :Make %><br />
   <%= m.text_field :tag_list %>
 </div>
 <% end %>
 <%= fields_for(@supercar.car_model) do |c| %>
 <div class="field">
   <%= c.label :Model %><br />
   <%= c.text_field :tag_list %>
 </div>
 <% end %>
 <%= fields_for(@supercar.city) do |i| %>
 <div class="field">
   <%= i.label :City %><br />
   <%= i.text_field :tag_list %>
 </div>
 <% end %>
 <%= fields_for(@supercar.country) do |o| %>
 <div class="field">
   <%= o.label :Country %><br />
   <%= o.text_field :tag_list %>
 </div>
 <% end %>
 <div class="field">
   <%= f.label :img_url %><br />
   <%= f.text_field :img_url %>
 </div>
 <div class="actions">
   <%= f.submit %>
 </div>
 <% end %>

app/views/supercars/index.html.erb
<h1>All the supercars, dawg!</h1>
<br>

<h4>Most Recently Indexed Supercars</h4>
<br>

<div class="index-top-container">
  <div class="index-top-left-list" style="display:inline-block;">
 <div class = "table-responsive">
    <table class="table table-striped">
      <tr>
        <th><h3>Make</h3></th>
        <th><h3>Model</h3></th>
        <th><h3>City</h3></th>
        <th><h3>Country</h3></th>
        <th><h3>Spotted By</h3></th>
        <th></th>
      </tr>
      <% @supercars.each do |supercar| %>
        <tr>
          <td>
            <h5>
              <% if supercar.make.tag_list.count %>
                <% supercar.make.tag_list.each do |tag| %>
                  <p><%= link_to tag, makes_tag_path(tag) %></p>
                <% end %>
              <% else %>
              <% end %>
            </h5>
          </td>
          <td>
          <h5>
              <% if supercar.car_model.tag_list.count %>
                <% supercar.car_model.tag_list.each do |tag| %>
                  <p><%= link_to tag, models_tag_path(tag) %></p>
                <% end %>
              <% else %>
              <% end %>
            </h5>
            </td>
          <td><h5><%= link_to supercar.city.tag_list, cities_tag_path(supercar.city.tag_list) %></h5></td>
          <td><h5><%= link_to supercar.country.tag_list, countries_tag_path(supercar.country.tag_list) %></h5></td>
          <td> 
            <% if supercar.user %>
              <%= supercar.user.username %>
            <% else %>
            <% end %>
          </td>
          <td> <%= link_to 'Edit', edit_supercar_path(supercar) %> </td>   
        </tr>
      <% end %>
    </table>
    </div>
    </div>
    <div class="index-ad-space" style="display:inline-block;width:30%;float:right;">
    <br>
      <div class="row">
        <div class="col-lg-12">
          <div class="input-group">        
            <input type="text" class="form-control" placeholder="Search for Manufacturer...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div>
      <br>
      <div class="row">
        <div class="col-lg-12">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for Model...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div>
      <br>
       <div class="row">
        <div class="col-lg-12">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for City...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div>
      <br>
       <div class="row">
        <div class="col-lg-12">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for Country...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div>
      <div style="text-align: right;">
       <%= will_paginate @supercars, renderer: BootstrapPagination::Rails %>  
      </div>
    </div>
  
  </div><!-- /.inex-top-container -->

<br>

<div class="container" id="tourpackages-carousel">
  <% @supercars.each_slice(3).each do |group| %>
      <div class="row">
      <% group.each do |supercar| %>
        <div id ="thumb-grid" class="col-xs-18 col-sm-6 col-m-4 col-lg-4">
          <div class="thumbnail">
            <div class = "insta-thumb">       
              <% resource = OEmbed::Providers::Instagram.get("#{supercar.img_url}") %>           
              <%= render :inline => resource.html.html_safe %>
            </div>
            <div class="caption">
            <div id="thumbnail-left-info" >
               <h3>City:</h3>  
              <h5><%= link_to supercar.city.tag_list, cities_tag_path(supercar.city.tag_list) %></h5>
              <h3>Country:</h3>
              <h5><%= link_to supercar.country.tag_list, countries_tag_path(supercar.country.tag_list) %></h5>
              <% if supercar.user %>
                  <h3>Spotted by:</h3>
                  <p><%= supercar.user.username %></p>
                <% else %>
              <% end %>
            </div>
            <div id="thumbnail-right-info">              
              <h3>Manufacturer:</h3>       
              
              <% if supercar.make.tag_list.count %>
<!--                 <h5><%= link_to supercar.car_model.tag_list, models_tag_path(supercar.car_model.tag_list) %></h5>
 -->                  <% supercar.make.tag_list.each do |tag| %>
                  <p><%= link_to tag, makes_tag_path(tag) %></p>
                <% end %>
              <% else %>
              <% end %>             

<!-- for tagged when tagged link routes ares working
              <% if supercar.make.tag_list.count %>
                <% supercar.make.tag_list.each do |tag| %>
                  <p><%= link_to tag, makes_tag_path(tag) %></p>
                <% end %>
              <% else %>
              <% end %>
               -->
              
              <h3>Model:</h3>

              <h5>
              <% if supercar.car_model.tag_list.count %>
<!--               <h5><%= link_to supercar.make.tag_list, makes_tag_path(supercar.make.tag_list) %></h5>
 -->              <% supercar.car_model.tag_list.each do |tag| %>
                      <p><%= link_to tag, models_tag_path(tag) %></p>
                <% end %>
              <% else %>
              <% end %>
              
<!-- for tagged when tagged link routes ares working
              <% if supercar.car_model.tag_list.count %>
                <% supercar.car_model.tag_list.each do |tag| %>
                  <p><%= link_to tag, models_tag_path(tag) %></p>
                <% end %>
              <% else %>
              <% end %>
               -->
              </h5> 
            </div>          
             
                                                           
            </div>
          </div>
        </div>
      <% end %>
    </div><!-- End row -->
  <% end %>
  <div style="text-align: right;"> 
  <%= will_paginate @supercars, renderer: BootstrapPagination::Rails %>
  </div>  
</div><!-- End container -->

app/views/supercars/new.html.erb
<% title("New Supercar") %>
<div class="row">
  <div class="col-sm-6">
    <h1>
      New Supercar 
    </h1>
    <p><%= link_to "Back to Supercars", supercars_path %></p>

    <%= form_for [@supercar] do |f| %>

    <%= fields_for(@supercar.make) do |m| %>

    <div class="form-group">
      <%= m.label :Manufacturer %>
      <div class="row">
        <div class="col-sm-6">
          <%= m.text_field :tag_list,:multiple => true, :autofocus => true, :parse => true, class: "form-control" %>
        </div>
      </div>
    </div>
    <% end %>

<!--     <%= fields_for(@supercar.make) do |m| %>

    <div class="form-group">
      <%= m.label :Manufacturername %>
      <div class="row">
        <div class="col-sm-6">
          <%= m.text_field :name,:multiple => true, :autofocus => true, :parse => true, class: "form-control" %>
        </div>
      </div>
    </div>
    <% end %>
 -->
    <%= fields_for(@supercar.car_model) do |c| %>

    <div class="form-group">
      <%= c.label :Model %>
      <div class="row">
        <div class="col-sm-6">
          <%= c.text_field :tag_list,:multiple => true, :autofocus => true, :parse => true, class: "form-control" %>
        </div>
      </div>
    </div>
    <% end %>
   
   <%= fields_for(@supercar.city) do |t| %>

    <div class="form-group">
      <%= t.label :City %>
      <div class="row">
        <div class="col-sm-6">
          <%= t.text_field :tag_list, :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>
    <% end %>

    <%= fields_for(@supercar.country) do |y| %>

    <div class="form-group">
      <%= y.label :Country %>
      <div class="row">
        <div class="col-sm-6">
          <%= y.text_field :tag_list, :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>
    <% end %>



<!-- 
      <div class="form-group">
      <%= f.label :Embeded_Instagram_Code %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.text_area :img_url, :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div> -->

          <div class="form-group">
      <%= f.label :Instagram_Image_URL %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_area :img_url, :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Create Supercars", class: "btn btn-danger" %>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/supercars/show.html.erb
<br>

<h4><%= link_to "Back to Supercars", supercars_url %> |  <%= link_to "Delete", @supercar, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"}  %></h4>


<br>
	<p><%= link_to @supercar.make.tag_list, makes_tag_path(@supercar.make.tag_list) %></p>
	<p><%= link_to @supercar.car_model.tag_list, models_tag_path(@supercar.car_model.tag_list) %></p>
	<p><%= link_to @supercar.city.tag_list, cities_tag_path(@supercar.city.tag_list) %></p>
	<p><%= link_to @supercar.country.tag_list, countries_tag_path(@supercar.country.tag_list) %></p>
	


	<%= render :inline => @supercar.img_url %>