config/routes.rb
SupercarIndexBricks::Application.routes.draw do
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

  resources :supercars do 
    collection do 
      get :tag
    end 
  end 

  resources :makes do 
    collection do 
      get :tag
    end 
  end

  resources :car_models do 
    collection do 
      get :tag
    end 
  end

  resources :cities do 
    collection do 
      get :tag
    end 
  end

  resources :countries do 
    collection do 
      get :tag
    end 
  end

  get 'makes/tags/:tag', to: 'makes#index', as: :makes_tag
  get 'models/tags/:tag', to: 'car_models#index', as: :models_tag
  get 'cities/tags/:tag', to: 'cities#index', as: :cities_tag
  get 'countries/tags/:tag', to: 'countries#index', as: :countries_tag

end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
  belongs_to :supercar
  has_one :rank
  
  acts_as_taggable
  acts_as_taggable_on :tags, :names

  validates_presence_of :tag_list, :on => :create

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :supercar
  has_one :rank
  
  acts_as_taggable
  acts_as_taggable_on :tags

  validates_presence_of :tag_list, :on => :create
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :supercar
  acts_as_taggable
  acts_as_taggable_on :tags

  validates_presence_of :tag_list, :on => :create
end

app/models/make.rb
class Make < ActiveRecord::Base
  belongs_to :supercar
  has_one :rank
  acts_as_taggable
  acts_as_taggable_on :tags, :name
  validates_presence_of :tag_list, :on => :create
end

app/models/post.rb
class Post < ActiveRecord::Base
  # Use friendly_id
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Markdown
  before_save { MarkdownWriter.update_html(self) }

  # Validations
  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :content_md, presence: true

  # Pagination
  paginates_per 30

  # Relations
  belongs_to :user

  # Scopes
  scope :published, lambda {
    where(draft: false)
    .order("updated_at DESC")
  }

  scope :drafted, lambda {
    where(draft: true)
    .order("updated_at DESC")
  }

end

app/models/rank.rb
class Rank < ActiveRecord::Base
	belongs_to :make
	belongs_to :car_model
	belongs_to :city
	belongs_to :country

	belongs_to :supercar
end

app/models/spot_type.rb
class SpotType < ActiveRecord::Base
  belongs_to :supercar
  has_one :rank
  
  acts_as_taggable
  acts_as_taggable_on :tags

  validates_presence_of :tag_list, :on => :create
end

app/models/supercar.rb
class Supercar < ActiveRecord::Base

	has_one :make
	has_one :car_model
	has_one :city
	has_one :country
	has_one :spot_type

	has_one :rank

	belongs_to :user
	
	accepts_nested_attributes_for :make, :car_model, :city, :country
	validates_presence_of :img_url, :on => :create	
	validates_format_of :img_url, :with => /instagram\.com\/p\/*/

	# e.g validates_format_of :video_link, :with => /youtu\.be\/([^\?]*)/ || /^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/


end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged

  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
# Relations
has_many :supercars
has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  # , :confirmable

  # Pagination
  paginates_per 100

  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..15 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end

  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end

  def self.last_signins(count)
    order(last_sign_in_at:
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end

  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def index
	if params[:tag]
	    @cities = City.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 6).order("created_at DESC")
	  else
	    @cities = City.all.paginate(:page => params[:page], :per_page => 6).order("created_at DESC")
	    render :allcities
	  end
	end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
	before_action :tag_cloud

	def index
	if params[:tag]
	    @makes = Make.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 6).order("created_at DESC")
	  else
	    @makes = Make.all.paginate(:page => params[:page], :per_page => 6).order("created_at DESC")
	    render :allmakes
	  end
	end

  def tag_cloud
    @tags = CarModel.tag_counts_on(:tags)
  end

  def tag
    @makes = Make.tagged_with(params[:name])
    @makes = Make.tag_counts_on(:tags)
    render :action => 'index'

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [
    :inside
  ]

  def home
  end

  def inside
  end
  
def posts
    @posts = Post.published.page(params[:page]).per(10)
  end
  
  def show_post
    @post = Post.friendly.find(params[:id])
  rescue
    redirect_to root_path
  end

  
  def email
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    
    if @name.blank?
      flash[:alert] = "Please enter your name before sending your message. Thank you."
      render :contact
    elsif @email.blank? || @email.scan(/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i).size < 1
      flash[:alert] = "You must provide a valid email address before sending your message. Thank you."
      render :contact
    elsif @message.blank? || @message.length < 10
      flash[:alert] = "Your message is empty. Requires at least 10 characters. Nothing to send."
      render :contact
    elsif @message.scan(/<a href=/).size > 0 || @message.scan(/\[url=/).size > 0 || @message.scan(/\[link=/).size > 0 || @message.scan(/http:\/\//).size > 0
      flash[:alert] = "You can't send links. Thank you for your understanding."
      render :contact
    else    
      ContactMailer.contact_message(@name,@email,@message).deliver_now
      redirect_to root_path, notice: "Your message was sent. Thank you."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | SupercarIndexBricks"
    end
  end
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def line_break(s)
    s.gsub("\n", "<br/>")
  end
end

app/helpers/makes_helper.rb
module MakesHelper
	  include ActsAsTaggableOn::TagsHelper
end

app/helpers/spot_types_helper.rb
module SpotTypesHelper
	  include ActsAsTaggableOn::TagsHelper
end

app/helpers/supercars_helper.rb
module SupercarsHelper
	require "oembed"
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - Nurbrun
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "All Supercars", supercars_path %></li>
<li><%= link_to "Manufacturers", makes_path %></li>
<li><%= link_to "Models", car_models_path %></li>
<li><%= link_to "Cities", cities_path %></li>
<li><%= link_to "Upload a Supercar", "/supercars/new" %></li>
<li><%= link_to "About This Index", contact_path %></li>
<% if !user_signed_in? %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
<li><%= link_to "Edit your account", edit_user_registration_path %></li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "SupercarIndex.net" %></title>
  <%= favicon_link_tag 'Lamborghini.png' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/contact.html.erb
<% title("Contact") %>
<h1 class="page-title">Contact</h1>

<div class="row">
  <div class="col-sm-6">

    <%= form_tag email_confirmation_path, method: 'post', html: {role: "form"} do %>

    <div class="form-group">
      <%= label_tag :name, "Your name" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_field_tag :name, @name, placeholder: "Enter your name...", :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :email, "Your email" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_field_tag :email, @email, placeholder: "Enter your email...", class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :message, "Your message" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_area_tag :message, @message, placeholder: "Enter your message...", rows: 10, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 padded">
        <button class='btn btn-primary'>
          <i class='fa fa-envelope'></i> Send
        </button>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1 style="text-align:right">
  #supercarindex that shit, yo
</h1>
<h3 style="text-align:right"> supercarindex.net </h3>

 <br>
<%= link_to image_tag("DSC_00642.jpg", :style => "width:55vw; display: block; margin-left: auto; margin-right: auto"), supercars_path, :class => "home-nurbrun"  %>

<!-- 
          <div class="thumbnail" id="home-nurbrun">
          <div class = "insta-thumb">
             <blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/qXj5WEqDvt/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Tucked away at the Hazleton</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Bruno A R (@nurbrun) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2014-07-12T22:41:46+00:00">Jul 12, 2014 at 3:41pm PDT</time></p></div></blockquote>
							<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
          </div>
            <div class="caption">
              <br>
                    
              <h4>Manufacturer:</h4>
              <h5><%= link_to 'Ferrari', '/makes/tags/Ferrari' %></h5>
              <h4>Model:</h4>
              <h5><%= link_to 'Enzo', '/models/tags/Enzo' %></h5>  
              <h4>City:</h4>
              <h5><%= link_to 'Toronto', '/cities/tags/Toronto' %></h5>  
              <h4>Country:</h4>
              <h5><%= link_to 'Canada', '/countries/tags/Canada' %></h5>
                  <h4>Spotted by:</h4>
                  <h5>nurbrun</h5>
                                              
            </div>
          </div>
 -->

app/views/pages/inside.html.erb
<% title("Protected page") %>
<h1>Protected Page</h1>
<p>This page is only visible to signed in users. Edit it at: <em>views/pages/inside.html.erb</em></p>
<p>You can change the page users see after successfully signing in within the method <em>after_sign_in_path_for</em> inside <strong>application_controller.rb</strong></p>

app/views/pages/posts.html.erb
<% title("Posts") %>
<h1>Posts</h1>

<% @posts.each do |post| %>

<div class="title-box">
  <p>
    <%= link_to "#{post.title}", post_path(post.slug) %> <br/>
    <span><small><em><%= time_ago_in_words(post.updated_at) %> ago</em></small></span>
  </p>

</div>

<% end %>

<div class="pagination-control text-center">
  <%= paginate @posts %>
</div>

app/views/pages/show_post.html.erb
<% title(@post.title) %>

<div class="row">
  <div class="col-sm-3"><h3><small><i class="fa fa-calendar"></i>&nbsp;&nbsp;<%= @post.updated_at.strftime("%Y, %B %-d") %></small></h3></div>
  <div class="col-sm-9"><%= @post.content_html.html_safe %></div>
</div>